"""add unique pending payment per invoice

Revision ID: 5709c4214853
Revises: a33a637e62ef
Create Date: 2026-09-27 02:34:24.814216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5709c4214853'
down_revision: Union[str, Sequence[str], None] = 'a33a637e62ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('payments_one_pending_per_invoice_idx', 'payments', ['invoice_id'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('payments_one_pending_per_invoice_idx', table_name='payments', postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###
